### PR TITLE
TEST: NOT A REAL PULL REQUEST

### PR DESCRIPTION
**Pull request by benpate**
I'll update this pull request later with a better description.  It's a test to see how the Travis-CI builds are working.

### CODE REVIEW

**Comment by benpate** [comment]
ok.  working so far...

**Comment by benpate** [comment]
I think that's all of the functional code.  So, let's try to run some tests...

**Comment by BrandonRomano** [comment]
This issue is melting my brain, I don't understand why this isn't working

**Comment by BrandonRomano** [comment]
Okay, I've just convinced myself this has to be a caching issue on travis's end.

Look at this log here:

```
The command "$HOME/gopath/bin/gom install" exited with 0.
0.34s$ cd test; $HOME/gopath/bin/gom test
# github.com/BrandonRomano/wrecker/test
./interceptor_test.go:14: undefined: wrecker.NewPlsWork
./interceptor_test.go:17: undefined: wrecker.PlsWork
FAIL    github.com/BrandonRomano/wrecker/test [build failed]
gom:  exit status 2
```

for this code:

test file:

``` go
func TestInterceptorGet(t *testing.T) {

    wrecker.New("http://localhost:" + os.Getenv("PORT"))

    newPlsWork := wrecker.NewPlsWork()
    fmt.Println(newPlsWork.Value)

    plswork := wrecker.PlsWork{
        Value: 100,
    }

    fmt.Println(plswork.Value)
    // ...
}
```

wrecker.go

``` go
type PlsWork struct {
    Value int
}

func NewPlsWork() PlsWork {
    return PlsWork{
        Value: 1100,
    }
}

type Wrecker struct {
    BaseURL            string
    HttpClient         *http.Client
    DefaultContentType string
    Interceptors       []Interceptor
}

func New(baseUrl string) *Wrecker {
    return &Wrecker{
        BaseURL: baseUrl,
        HttpClient: &http.Client{
            Timeout: 10 * time.Second,
        },
        DefaultContentType: "application/x-www-form-urlencoded",
    }
}
```

There's no `undefined` nonsense for `New`, so we can rule out the possibility of the whole `wrecker.go` file not loading.

These tests are all passing locally (or giving me the output I expect).

I'm going to reach out to some of my co workers to see if they've ever experienced anything like this

**Comment by BrandonRomano** [comment]
So I was able to successfully use the same logic on #36 with success...  Not sure why.  Still digging

**Pull request closed without merging**
