### PR TITLE
Request interceptor

### PR DESCRIPTION
**Pull request by benpate**
This addresses issue #4

### CODE REVIEW

**Comment by benpate** [comment]
Hey @BrandonRomano ,

I'm not exactly sure why this is failing.  The notes from Travis make it seem like it can't find the /interceptors directory.  That's a new package I made to put some simple/sample interceptors into.  

Do you think you could take a look at it to see if there's some extra configuration required?

## 

Ben

**Comment by BrandonRomano** [comment]
Hey Ben,

Yeah I'll look into this tonight for you.  Sorry took so long to respond -- had a busy weekend!

**Comment by BrandonRomano** [comment]
This is the problem we're running into:

http://stackoverflow.com/questions/22432202/cannot-find-package-on-travis-ci-golang.

I have a private repo hooked up to travis with this same exact case and I'm not running into any issues...  I'm going to look into this some more!

**Comment by BrandonRomano** [comment]
Hmm.  This is a tricky one.

Look at the last logs:

I run this:

```
$ pwd; ls -la;
```

With the output:

```
/home/travis/gopath/src/github.com/BrandonRomano/wrecker
total 36
drwxrwxr-x 5 travis travis 4096 Jun 30 00:14 .
drwxrwxr-x 3 travis travis   20 Jun 30 00:15 ..
drwxrwxr-x 8 travis travis 4096 Jun 30 00:14 .git
-rw-rw-r-- 1 travis travis   36 Jun 30 00:14 .gitignore
-rw-rw-r-- 1 travis travis   76 Jun 30 00:14 Gomfile
drwxrwxr-x 2 travis travis   29 Jun 30 00:14 interceptors
-rw-rw-r-- 1 travis travis 1081 Jun 30 00:14 LICENSE.md
-rw-rw-r-- 1 travis travis 2399 Jun 30 00:14 README.md
-rw-rw-r-- 1 travis travis 1036 Jun 30 00:14 request.go
drwxrwxr-x 3 travis travis  102 Jun 30 00:14 test
-rw-rw-r-- 1 travis travis  186 Jun 30 00:14 .travis.yml
-rw-rw-r-- 1 travis travis 3201 Jun 30 00:14 wrecker.go
```

And also

```
0.00s$ ls -la interceptors/ 
```

With the output:

```
total 8
drwxrwxr-x 2 travis travis   29 Jun 30 00:14 .
drwxrwxr-x 5 travis travis 4096 Jun 30 00:14 ..
-rw-rw-r-- 1 travis travis  427 Jun 30 00:14 authorization.go
```

And here is the remainder of the relevant output:

```
4.36s$ go get -t -v ./...
github.com/brandonromano/wrecker (download)
github.com/julienschmidt/httprouter (download)
package github.com/brandonromano/wrecker
    imports github.com/julienschmidt/httprouter
    imports github.com/brandonromano/wrecker/interceptors
    imports github.com/brandonromano/wrecker/interceptors
    imports github.com/brandonromano/wrecker/interceptors: cannot find package "github.com/brandonromano/wrecker/interceptors" in any of:
    /home/travis/.gimme/versions/go/src/github.com/brandonromano/wrecker/interceptors (from $GOROOT)
    /home/travis/gopath/src/github.com/brandonromano/wrecker/interceptors (from $GOPATH)
github.com/stretchr/testify (download)
The command "eval go get -t -v ./..." failed. Retrying, 2 of 3.
```

It says it `cannot find package "github.com/brandonromano/wrecker/interceptors" in any of ... /home/travis/gopath/src/github.com/brandonromano/wrecker/interceptors`, when we have just checked that the directory has the files above.

Something really strange is going on, I'm going to create a new GOPATH on my local machine and try to reproduce this one.

**Comment by BrandonRomano** [comment]
Hey @benpate... Check out the [travis-test](https://github.com/BrandonRomano/wrecker/tree/travis-test) branch.  I was able to have the branch [successfully pass](https://travis-ci.org/BrandonRomano/wrecker/builds/68974155) with a nested package.

I'm quite busy today and don't have the time to dig into your source to compare, but if you've got some time feel free to check out that branch, maybe you'll get some insight.

I'll be checking the two of them tonight if you've not figured it out!

**Comment by BrandonRomano** [comment]
@benpate Have you got any idea why this is failing?  I remember I took a look at this issue and couldn't figure it out...

I would like to have this thing passing before I take a good look at it.

**Comment by benpate** [comment]
I'm closing this PR in favor of several smaller PRs that should be easier to test and merge.

**Comment by BrandonRomano** [comment]
Thanks @benpate -- much appreciated :tada:

**Pull request closed without merging**
